import type { RadarPayload } from "./types";

// This is a recorded fixture, not live data. A fixed reference instant keeps
// server rendering and browser hydration byte-for-byte deterministic.
const demoRecordedAt = new Date("2026-07-16T20:27:00.000Z");
const t = (hoursAgo: number) => new Date(demoRecordedAt.getTime() - hoursAgo * 3_600_000).toISOString();

export const demoPayload: RadarPayload = {
  generatedAt: demoRecordedAt.toISOString(),
  dataMode: "recorded_demo",
  window: "6h",
  sort: "latest",
  totalEvents: 5,
  limit: 200,
  hasMore: false,
  events: [
    {
      id: "evt-open-model",
      title: "开放权重多模态模型发布引发跨平台采用",
      titleEn: "Open-weight multimodal model sees cross-platform adoption",
      eventType: "model_release",
      state: "accelerating",
      labels: ["cross_platform_confirmed", "adoption_confirmed", "official_source_led"],
      attention: 84,
      behavior: 78,
      diversity: 76,
      authority: 88,
      coordinationRisk: 18,
      coverage: 86,
      uncertainty: 12,
      evidenceStrength: "high",
      evidenceScore: 90,
      velocity: 22,
      gapResidual: 4,
      firstSeen: t(5.7),
      updatedAt: t(0.1),
      independentSources: 43,
      platforms: ["Official", "GitHub", "Hugging Face", "HN"],
      driver: "讨论或采用行为连续两个周期保持正增长；GitHub 与 Hugging Face 增长并非由单一平台贡献。",
      coverageNote: "四个独立信号家族均有数据，外部社交平台仅作辅助证据。",
      timeline: [
        { at: t(6), attention: 28, behavior: 22 }, { at: t(5), attention: 39, behavior: 31 },
        { at: t(4), attention: 48, behavior: 43 }, { at: t(3), attention: 61, behavior: 55 },
        { at: t(2), attention: 73, behavior: 67 }, { at: t(1), attention: 80, behavior: 73 },
        { at: t(0), attention: 84, behavior: 78 },
      ],
      evidence: [
        { id: "e1", source: "Model Lab", platform: "Official", title: "官方模型卡与发布说明", url: "https://example.com/model-card", publishedAt: t(5.8), kind: "official", excerpt: "发布公告包含权重、许可证、评测及推理示例。" },
        { id: "e2", source: "GitHub", platform: "GitHub", title: "推理仓库 6 小时新增 1.8k stars", url: "https://github.com/", publishedAt: t(4.9), kind: "behavior", excerpt: "去除历史基线后，star 与 fork 增速均超过 MAD 异常阈值。" },
        { id: "e3", source: "Hugging Face", platform: "Hugging Face", title: "模型下载与衍生模型同步上升", url: "https://huggingface.co/", publishedAt: t(4.5), kind: "behavior", excerpt: "下载、点赞及衍生模型来自多个独立作者。" },
        { id: "e4", source: "Hacker News", platform: "HN", title: "开发者讨论进入首页", url: "https://news.ycombinator.com/", publishedAt: t(3.7), kind: "discussion", excerpt: "独立评论者数量增长，重复转述已完成去重。" },
      ],
    },
    {
      id: "evt-agent-campaign",
      title: "“自主智能体平台”密集宣发但开发者采用未跟进",
      titleEn: "Agent platform campaign lacks adoption follow-through",
      eventType: "developer_tool_release",
      state: "emerging",
      labels: ["attention_behavior_gap", "coordination_risk", "low_source_diversity"],
      attention: 81,
      behavior: 34,
      diversity: 42,
      authority: 58,
      coordinationRisk: 78,
      coverage: 79,
      uncertainty: 21,
      evidenceStrength: "high",
      evidenceScore: 75,
      velocity: 12,
      gapResidual: 36,
      firstSeen: t(8.2),
      updatedAt: t(0.3),
      independentSources: 18,
      platforms: ["RSS", "YouTube", "Official"],
      driver: "关注度显著高于同类工具发布的预期采用曲线，且 63% 的首轮内容集中在同一发布窗口。",
      coverageNote: "讨论覆盖良好；代码采用与包下载已覆盖，但付费转化不可见。",
      timeline: [
        { at: t(6), attention: 44, behavior: 20 }, { at: t(5), attention: 58, behavior: 22 },
        { at: t(4), attention: 70, behavior: 25 }, { at: t(3), attention: 76, behavior: 28 },
        { at: t(2), attention: 79, behavior: 31 }, { at: t(1), attention: 81, behavior: 33 },
        { at: t(0), attention: 81, behavior: 34 },
      ],
      evidence: [
        { id: "e5", source: "Official blog", platform: "Official", title: "产品发布说明", url: "https://example.com/launch", publishedAt: t(8.2), kind: "official", excerpt: "官方同步公布产品功能与合作伙伴内容。" },
        { id: "e6", source: "Monitored feeds", platform: "RSS", title: "14 个账号在 27 分钟内发布", url: "https://example.com/coordinated", publishedAt: t(7.8), kind: "discussion", excerpt: "文本相似度、发布时间和链接目标存在显著重合。" },
        { id: "e7", source: "Package registry", platform: "GitHub", title: "安装与 fork 增长低于同类基线", url: "https://github.com/", publishedAt: t(2.1), kind: "behavior", excerpt: "观察窗内采用指标未超过正常波动范围。" },
      ],
    },
    {
      id: "evt-benchmark",
      title: "新推理基准结果在研究者圈层快速扩散",
      titleEn: "Reasoning benchmark spreads through research circles",
      eventType: "research_or_benchmark",
      state: "emerging",
      labels: ["expected_behavior_lag", "official_source_led"],
      attention: 62,
      behavior: 41,
      diversity: 67,
      authority: 82,
      coordinationRisk: 12,
      coverage: 71,
      uncertainty: 27,
      evidenceStrength: "high",
      evidenceScore: 73,
      velocity: 18,
      gapResidual: 8,
      firstSeen: t(3.7),
      updatedAt: t(0.2),
      independentSources: 11,
      platforms: ["arXiv", "OpenAlex", "GitHub"],
      driver: "五个高领先度研究信源在两个独立群体中讨论；论文类事件的采用行为存在正常延迟。",
      coverageNote: "研究源与代码源可见，社交讨论覆盖有限，因此不输出破圈结论。",
      timeline: [
        { at: t(4), attention: 18, behavior: 10 }, { at: t(3.3), attention: 27, behavior: 14 },
        { at: t(2.6), attention: 39, behavior: 21 }, { at: t(2), attention: 48, behavior: 28 },
        { at: t(1.3), attention: 56, behavior: 35 }, { at: t(0.6), attention: 62, behavior: 41 },
      ],
      evidence: [
        { id: "e8", source: "arXiv", platform: "arXiv", title: "论文预印本", url: "https://arxiv.org/", publishedAt: t(3.7), kind: "research", excerpt: "论文提出基准构造与可复现评测协议。" },
        { id: "e9", source: "OpenAlex", platform: "OpenAlex", title: "研究实体与作者网络", url: "https://openalex.org/", publishedAt: t(3.1), kind: "discussion", excerpt: "早期讨论来自两个独立研究群体。" },
        { id: "e10", source: "GitHub", platform: "GitHub", title: "评测代码仓库开始增长", url: "https://github.com/", publishedAt: t(1.8), kind: "behavior", excerpt: "复现实验与 issue 数量进入加速区间。" },
      ],
    },
    {
      id: "evt-video-spike",
      title: "单平台 AI 视频演示播放量异常脉冲",
      titleEn: "Single-platform AI video demo spike",
      eventType: "official_product_release",
      state: "detected",
      labels: ["platform_concentrated", "low_source_diversity"],
      attention: 38,
      behavior: 76,
      diversity: 21,
      authority: 33,
      coordinationRisk: 30,
      coverage: 68,
      uncertainty: 32,
      evidenceStrength: "medium",
      evidenceScore: 64,
      velocity: 8,
      gapResidual: -31,
      firstSeen: t(2.6),
      updatedAt: t(0.1),
      independentSources: 4,
      platforms: ["YouTube"],
      driver: "87% 行为增长集中在单平台，独立讨论者和跨平台迁移没有同步增加。",
      coverageNote: "YouTube 数据完整；其他讨论与采用源未发现对应增长。",
      timeline: [
        { at: t(3), attention: 17, behavior: 20 }, { at: t(2.5), attention: 21, behavior: 39 },
        { at: t(2), attention: 26, behavior: 58 }, { at: t(1.5), attention: 31, behavior: 70 },
        { at: t(1), attention: 35, behavior: 75 }, { at: t(0), attention: 38, behavior: 76 },
      ],
      evidence: [
        { id: "e11", source: "YouTube", platform: "YouTube", title: "播放量进入推荐脉冲", url: "https://youtube.com/", publishedAt: t(2.4), kind: "behavior", excerpt: "观看增量高度集中于单条视频，评论者数量未同步增长。" },
        { id: "e12", source: "Cross-platform check", platform: "RSS", title: "其他平台无对应迁移", url: "https://example.com/check", publishedAt: t(0.5), kind: "discussion", excerpt: "监测平台中尚未出现独立信源扩散。" },
      ],
    },
    {
      id: "evt-security",
      title: "主流推理框架披露高危供应链漏洞",
      titleEn: "Critical supply-chain issue in inference framework",
      eventType: "security_incident",
      state: "accelerating",
      labels: ["cross_platform_confirmed", "official_source_led"],
      attention: 74,
      behavior: 69,
      diversity: 71,
      authority: 93,
      coordinationRisk: 7,
      coverage: 91,
      uncertainty: 9,
      evidenceStrength: "high",
      evidenceScore: 94,
      velocity: 29,
      gapResidual: 2,
      firstSeen: t(1.9),
      updatedAt: t(0.05),
      independentSources: 27,
      platforms: ["GitHub", "Official", "HN", "RSS"],
      driver: "官方安全公告、补丁下载与开发者讨论同步增长，影响范围跨越多个生态。",
      coverageNote: "安全公告、仓库事件和技术讨论均可核验。",
      timeline: [
        { at: t(2), attention: 21, behavior: 16 }, { at: t(1.6), attention: 34, behavior: 27 },
        { at: t(1.2), attention: 48, behavior: 39 }, { at: t(0.8), attention: 61, behavior: 55 },
        { at: t(0.4), attention: 69, behavior: 63 }, { at: t(0), attention: 74, behavior: 69 },
      ],
      evidence: [
        { id: "e13", source: "Security advisory", platform: "Official", title: "官方安全公告与修复版本", url: "https://github.com/advisories", publishedAt: t(1.9), kind: "official", excerpt: "公告包含受影响版本、缓解措施与补丁。" },
        { id: "e14", source: "GitHub", platform: "GitHub", title: "补丁版本下载快速增长", url: "https://github.com/", publishedAt: t(1.5), kind: "behavior", excerpt: "多个依赖项目已更新锁文件。" },
        { id: "e15", source: "Hacker News", platform: "HN", title: "维护者与开发者交叉验证", url: "https://news.ycombinator.com/", publishedAt: t(1.1), kind: "discussion", excerpt: "讨论包含复现、影响分析与升级反馈。" },
      ],
    },
  ],
  connectors: [
    { id: "rss", name: "RSS / 官方站点", family: "官方与媒体", status: "healthy", latencyMinutes: 3, observations24h: 1284, coverage: 94, lastSuccess: t(0.05), note: "142 个订阅源，正文指纹去重已启用" },
    { id: "hn", name: "Hacker News", family: "技术讨论", status: "healthy", latencyMinutes: 2, observations24h: 842, coverage: 98, lastSuccess: t(0.03), note: "官方 API；评论作者按独立讨论者计算" },
    { id: "github", name: "GitHub", family: "开发者行为", status: "healthy", latencyMinutes: 6, observations24h: 3621, coverage: 91, lastSuccess: t(0.08), note: "仓库事件、搜索与指标快照" },
    { id: "hf", name: "Hugging Face", family: "模型采用", status: "healthy", latencyMinutes: 7, observations24h: 1047, coverage: 89, lastSuccess: t(0.1), note: "Hub API；下载、点赞和衍生关系" },
    { id: "research", name: "arXiv / OpenAlex", family: "研究信号", status: "healthy", latencyMinutes: 11, observations24h: 516, coverage: 86, lastSuccess: t(0.15), note: "跨语言实体与作者网络归并" },
    { id: "youtube", name: "YouTube", family: "内容行为", status: "degraded", latencyMinutes: 19, observations24h: 431, coverage: 58, lastSuccess: t(0.32), note: "配额降频中；结论自动降低覆盖置信度" },
    { id: "x", name: "X Recent Search", family: "社交讨论", status: "paused", latencyMinutes: 0, observations24h: 0, coverage: 0, lastSuccess: t(48), note: "实验连接器，未配置商业数据授权" },
  ],
};
